.env.example
docker-compose.yml
frontend/.dockerignore
frontend/Dockerfile

This pull request:
- adds a switch in the `.env` to build a development or production image
- reduces the size of the build context for the image and hence the loading time for building

feat: frontend: a better image for the frontend

---

backend/.dockerignore
backend/Dockerfile
docker-compose.yml

- Change backend to use env variable for node image version
- Add .dockerignore to backend to speed up build times
- Clean backend Dockerfile
Fix #14
Fix #15

fix(docker): backend: update Dockerfile

---

backend/src/messages/dto/message.dto.ts
backend/src/messages/entities/message.entity.ts

- update entity
- update dto
- fix #31

feat(messages): add timestamp

---

CONTRIBUTING.md

- CONTRIBUTING.md
- subject (up-to-date on the 07-16-22) to have it available by public
link and as specification of sorts

docs: adding extraneous documentation

---

.env.example

Add dummy value to every entries.
Comments have now their own line.
Add comments to explain some of the options available.

docs: reformat .env.example

---

frontend/Dockerfile
frontend/nginx.conf

- added a custom nginx configuration, with ``` try_files $uri $uri/ /index.html ``` to redirect ```/some-route``` to ```index.html```
- edited the frontend Dockerfile to copy the custom conf in ```/etc/nginx/nginx.conf```

fix(frontend): no more 404 when a route is reloaded

---

.gitignore
backend/package.json
backend/src/channels/channels.controller.spec.ts
backend/src/channels/channels.service.spec.ts
backend/src/common/dto/page-options.dto.ts
backend/src/common/mocks/repository.mock.ts
backend/src/memberships/memberships.controller.spec.ts
backend/src/memberships/memberships.service.spec.ts
backend/src/messages/messages.controller.spec.ts
backend/src/messages/messages.controller.ts
backend/src/messages/messages.service.spec.ts
backend/src/relationships/relationships.controller.spec.ts
backend/src/relationships/relationships.service.spec.ts
backend/src/users/mocks/user.entity.mock.ts
backend/src/users/users.controller.spec.ts
backend/src/users/users.service.spec.ts

Add tests for the backend API. These tests will require updating, but it should give us a foundation to build on.
fix #33

test(backend): add and update tests

---

frontend/src/assets/images/GitHub-Mark-120px-plus.png
frontend/src/assets/images/abouchau.jpg
frontend/src/assets/images/fyusuf-a.jpg
frontend/src/assets/images/mdesfont.jpg
frontend/src/assets/images/tmorris.jpg
frontend/src/assets/images/tvideira.jpg
frontend/src/components/Team/TeamCard.vue
frontend/src/views/AboutView.vue

refactor(frontend): improve the About page
- to fix: download of the subject not working, 404
fix(frontend): modify the link to the subject, now pointing to out
README.md
refactor(frontend): cleaning some code

feat(frontend): create the About page

---

backend/src/app.module.ts
backend/src/common/dto/page.dto.ts
backend/src/matches/dto/create-match.dto.ts
backend/src/matches/dto/match.dto.ts
backend/src/matches/dto/query-match.dto.ts
backend/src/matches/dto/response-match.dto.ts
backend/src/matches/dto/update-match.dto.ts
backend/src/matches/entities/match.entity.ts
backend/src/matches/matches.controller.spec.ts
backend/src/matches/matches.controller.ts
backend/src/matches/matches.module.ts
backend/src/matches/matches.service.spec.ts
backend/src/matches/matches.service.ts
backend/src/matches/repository/match.repository.ts

I built a match entity, service and controller in `./backend/src/matches` as well as tests for the service and controller: `./backend/matches.service.spec` and `./backend/matches.controller.spec`.

test(backend): added a match entity, service and controller, and tests

---

.env.example
backend/src/main.ts

- remove hardcoded port 3000 from main.ts
- fix #83

feat(backend): add optional BACKEND_PORT

---

.github/workflows/backend-ci.yml
.github/workflows/cd.yml
.github/workflows/frontend-ci.yml

The diffs that were designed to conditionally run the jobs are fixed.

fix(ci/cd): gets the diffs right

---

.github/workflows/frontend-ci.yml
frontend/src/router/auth.ts
frontend/tests/unit/example.spec.ts

- fix type warnings due to use of `any`
- update example.spec.ts to test that the app mounts
- update frontend.yml to run linting with `--max-warnings=0` and unit tests
Fix #84

Update frontend linting and unit tests to be usable in CI

---

.github/semantic.yml

I installed the Github App [Semantic PR](https://github.com/Ezard/semantic-prs). It adds a status check for the PRs but needs some configuring.

feat(ci): configures conventional commits

---

frontend/src/views/AboutView.vue

- Remove members prop from team-card tag
Fix #131

fix: remove unused prop from team-card tag

---

frontend/package-lock.json
frontend/package.json
frontend/src/views/ChatView.vue
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tsconfig.json

Creates ChatView with a ChannelList and ChatWindow
- Can read old messages
- Receive new messages over sockets to instantly update a channel
- Send messages on a joined channel
STACKED: #139

feat(ChatView) create ChatView

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Chat/ChannelList.vue
frontend/src/views/ChatView.vue
frontend/tests/unit/Chat/ChannelList.spec.ts
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tsconfig.json

Creates ChannelList to list all channels which the user has joined.
- Shows an unread indicator on channels with newly received messages
Fix #52 
STACKED: #138

feat(ChatView): create ChannelList.vue

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/components/Chat/ChannelList.vue
frontend/src/views/ChatView.vue
frontend/tests/unit/Chat/ChannelJoinDialog.spec.ts
frontend/tests/unit/Chat/ChannelList.spec.ts
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tsconfig.json

Create ChatChannelJoinDialog which will be opened from ChannelList to display a list of channels which can be joined by the User.
- List of joinable channels
- Toggle to Create a channel if the desired channel is not found
Re: #52 
STACKED: #137

feat(ChatView): create ChatChannelJoinDialog.vue

---

frontend/package-lock.json
frontend/package.json
frontend/src/common/dto/channel.dto.ts
frontend/src/common/dto/membership.dto.ts
frontend/src/common/dto/message.dto.ts
frontend/src/common/dto/user.dto.ts
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/components/Chat/ChannelList.vue
frontend/src/components/Chat/ChatWindow.vue
frontend/src/components/Chat/ChatWindowMenu.vue
frontend/src/views/ChatView.vue
frontend/tests/unit/Chat/ChannelJoinDialog.spec.ts
frontend/tests/unit/Chat/ChannelList.spec.ts
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tests/unit/Chat/ChatWindow.spec.ts
frontend/tests/unit/Chat/ChatWindowMenu.spec.ts
frontend/tsconfig.json

Creates a menu which will be used by the Chat Window and contains channel related options:
- Leave channel
Re: #53 
STACKED: #135

feat(ChatView): create ChatWindowMenu.vue

---

frontend/package-lock.json
frontend/package.json
frontend/src/common/dto/channel.dto.ts
frontend/src/common/dto/membership.dto.ts
frontend/src/common/dto/message.dto.ts
frontend/src/common/dto/user.dto.ts
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/components/Chat/ChannelList.vue
frontend/src/components/Chat/ChatMessage.vue
frontend/src/components/Chat/ChatWindow.vue
frontend/src/components/Chat/ChatWindowMenu.vue
frontend/src/views/ChatView.vue
frontend/tests/unit/Chat/ChannelJoinDialog.spec.ts
frontend/tests/unit/Chat/ChannelList.spec.ts
frontend/tests/unit/Chat/ChatMessage.spec.ts
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tests/unit/Chat/ChatWindow.spec.ts
frontend/tests/unit/Chat/ChatWindowMenu.spec.ts
frontend/tsconfig.json

Creates a ChatMessage which will be used by ChatWindow to display the sender, contents, and timestamp of messages
- Display a message with timestamp and avatar
- includes ChatMessageMenu on avatar
Re: #53 
STACKED: #134

feat(ChatView): create ChatMessage.vue

---

frontend/package-lock.json
frontend/package.json
frontend/src/common/dto/channel.dto.ts
frontend/src/common/dto/membership.dto.ts
frontend/src/common/dto/message.dto.ts
frontend/src/common/dto/user.dto.ts
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/components/Chat/ChannelList.vue
frontend/src/components/Chat/ChatMessage.vue
frontend/src/components/Chat/ChatMessageMenu.vue
frontend/src/components/Chat/ChatWindow.vue
frontend/src/components/Chat/ChatWindowMenu.vue
frontend/src/views/ChatView.vue
frontend/tests/unit/Chat/ChannelJoinDialog.spec.ts
frontend/tests/unit/Chat/ChannelList.spec.ts
frontend/tests/unit/Chat/ChatMessage.spec.ts
frontend/tests/unit/Chat/ChatMessageMenu.spec.ts
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tests/unit/Chat/ChatWindow.spec.ts
frontend/tests/unit/Chat/ChatWindowMenu.spec.ts
frontend/tsconfig.json

Creates a menu which will open on ChatMessages to interact with other users.  (Options currently are present, but do nothing)
- has regular options:
- View Profile
- Challenge
- Friend
- Block
- Message
- has admin options (if client is admin)
- Mute
- Ban
Re: #53

feat(ChatView): create ChatMessageMenu.vue

---

frontend/src/assets/images/40cat.png
frontend/src/router/index.ts
frontend/src/views/NotFound.vue

- Caution: to test it, please comment lines 56 to 66 in the router index.ts (router.beforeEach()), and then try to access an non-existent page. The auth system on master prevents to find a 404 page. The router.beforeEach() will change with the 42API auth system, so we'll need to do the tests on this future version

feat(frontend): creation of the 404 view

---

.dockerignore
backend/Dockerfile.dockerignore
frontend/Dockerfile.dockerignore

refactor(frontend)!: migration to vue3, vuetify3 and vite

---

.github/workflows/backend-ci.yml
.github/workflows/frontend-ci.yml
backend/package.json
docker-compose.yml
frontend/Dockerfile
frontend/package-lock.json
frontend/package.json
frontend/src/shims-nestjs.d.ts
frontend/tests/unit/Chat/ChannelJoinDialog.spec.ts
frontend/tests/unit/Chat/ChannelList.spec.ts
frontend/tests/unit/Chat/ChatMessage.spec.ts
frontend/tests/unit/Chat/ChatMessageMenu.spec.ts
frontend/tests/unit/Chat/ChatView.spec.ts
frontend/tests/unit/Chat/ChatWindow.spec.ts
frontend/tests/unit/Chat/ChatWindowMenu.spec.ts
frontend/tests/unit/example.spec.ts
frontend/tests/vuetify-test.ts
frontend/tsconfig.json
frontend/vite.config.ts
frontend/vitest/beforeall.ts

Fixes the remaining vite and typescript errors.
Fixes ci to activate the CI on the `vue3-dev` branch

fix and test: fixes typescript errors and prepares status checks to be required on the vue3-dev branch

---

frontend/src/components/UI/TheNavigationDrawer.vue
frontend/src/views/UILayout.vue

The color of the drawer is OK on the list, and the drawer doesn't break the nav bar anymore

fix(frontend): The Navigation Bar and the Navigation Drawer are now positioned correctly and the Drawer color has been corrected

---

backend/src/matches/matches.controller.spec.ts
backend/src/memberships/memberships.controller.spec.ts
backend/src/memberships/memberships.controller.ts
backend/src/memberships/memberships.module.ts
backend/src/memberships/memberships.service.spec.ts
backend/src/memberships/memberships.service.ts
backend/test/membership.e2e-spec.ts
dtos/matches/create-match.dto.ts
dtos/matches/match.dto.ts
dtos/matches/query-match.dto.ts
dtos/matches/response-match.dto.ts
dtos/matches/update-match.dto.ts
dtos/memberships/create-membership.dto.ts
frontend/src/assets/images/40cat.png
frontend/src/views/NotFound.vue

Making `vue3-dev` up to date with `master`.

Fyusuf a/merge with master

---

dtos/achievements-log/create-achievements-log.dto.ts
dtos/achievements-log/response-achievements-log.dto.ts
dtos/achievements/create-achievement.dto.ts
dtos/achievements/response-achievement.dto.ts
dtos/auth/login-user.dto.ts
dtos/auth/token-user.dto.ts
dtos/blocks/create-block.dto.ts
dtos/blocks/response-block.dto.ts
dtos/blocks/update-block.dto.ts
dtos/channels/create-channel.dto.ts
dtos/channels/response-channel.dto.ts
dtos/channels/update-channel.dto.ts
dtos/friendships/create-friendship.dto.ts
dtos/friendships/update-friendship.dto.ts
dtos/matches/create-match.dto.ts
dtos/matches/update-match.dto.ts
dtos/memberships/create-membership.dto.ts
dtos/memberships/response-membership.dto.ts
dtos/memberships/update-membership.dto.ts
dtos/messages/create-message.dto.ts
dtos/messages/response-message.dto.ts
dtos/users/create-user.dto.ts
dtos/users/response-user.dto.ts
dtos/users/update-user.dto.ts
frontend/src/shims-nestjs.d.ts

fix: swagger shows DTOs

---

backend/src/relationships/blocks/blocks.controller.ts
backend/src/relationships/blocks/blocks.service.ts
backend/src/relationships/friendships/friendships.service.ts
backend/src/users/users.controller.ts
backend/src/users/users.service.ts
dtos/blocks/block.dto.ts
dtos/blocks/list-block.dto.ts
dtos/blocks/response-block.dto.ts
dtos/blocks/update-block.dto.ts
frontend/src/components/Profile/BlockUser.vue
frontend/src/components/Profile/MyFriends.vue

Very similar to how the AddFriend component works.
You can block users by usernames. If the user is your friend, the frienship is deleted. If you unblock them, the frienship isn't restore (it seems to me it was the most logical way to operate).
The features to be examined are the following:
- Block a user. It must appear in the list of blocked users (front), and the blocked relationship must have been created (back);
- Unblock a user. He must disappear from the list of blocked users (front), and the blocked relationship must have been deleted (back);
- Block a friend (an approved friend, to be clearer). The friend relationship must have been deleted;

feat(frontend): implementation of the functionality to block and unblock users

---

frontend/src/components/Game/GameWindow.vue
frontend/src/views/GameView.vue
frontend/src/views/NotFound.vue

- Frontend of the Game Page has been improved;
- Pong is now responsive;
King Pong works correctly, even when the window is resized in game.

feat(frontend): improvement of the game page and the game is responsive

---

frontend/src/components/Game/GameWindow.vue

Fix this error:
```A spectator receives the message that they lost at the end of the game```

fix(frontend): a spectator recieves another message when someone win

---

backend/src/memberships/memberships.controller.ts
frontend/src/components/Chat/ChatMessage.vue
frontend/src/components/Chat/ChatMessageMenu.vue
frontend/src/components/Chat/ChatWindow.vue
frontend/src/views/ChatView.vue

Make admins

---

frontend/src/views/ChatView.vue

When the 'Challenge' option is selected in the MessageMenu, the challengeUser  variable should be set in the store, and the user should be redirected to the GameView
Re: #292

feat(chat): redirect challenges to GameView

---

.env.example
README.md
backend/src/channels/channels.service.ts
docker-compose.yml

feat(hash): use env variable for rounds of hashing

---

frontend/src/components/Profile/Activate2FA.vue
frontend/src/store/index.ts

fix(frontend): fixes 2-factor authentication

---

frontend/src/components/Login/FortyTwo.vue
frontend/src/components/Login/TwoFA.vue

This allows users a button to login rather than being automatically logged in

feat(login): add a login button

---

frontend/src/App.vue
frontend/src/components/Chat/ChannelInviteDialog.vue
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/components/Chat/ChannelKarmaDialog.vue
frontend/src/components/Chat/ChannelPasswordDialog.vue
frontend/src/components/Game/GameWindow.vue
frontend/src/components/Profile/AddFriend.vue
frontend/src/components/Profile/BlockUser.vue
frontend/src/components/Profile/ChangeAvatar.vue
frontend/src/components/Profile/ChangeUsername.vue
frontend/src/components/Profile/MyMatchHistory.vue

With the packages updates, the ```v-dialog``` positions were broken.
It's now fix.

fix(frontend): fix position of dialog boxes

---

frontend/src/components/Profile/AddAsFriend.vue
frontend/src/components/Profile/AddFriend.vue

Before, we can add a user as friend, even if they are blocked. It's fixed.

fix(frontend): if a user is blocked, you can't add them as friend

---

backend/src/app.module.ts
backend/src/channels/channels.service.ts
backend/src/chat.gateway.ts
backend/src/memberships/memberships.service.ts
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/views/ChatView.vue

This fixes behavior when a channel is deleted or fails to be created
- users should see that they have been removed from channels when the channel is deleted (it should disappear from their ChannelList)
- users should be notified if they tried to create a channel and it failed

fix(chat): channel creation failure and deletion

---

frontend/src/views/ChatView.vue

fix(chat): fetch all messages in channel

---

frontend/src/components/Chat/ChatMessage.vue
frontend/src/views/ChatView.vue

- Move channel list to the left/top
- Put the timestamp into a tooltip
- Move the message and avatar onto a single line

Fix chat display

---

frontend/src/components/Profile/AddFriend.vue

refactor(frontend): display error on front

---

backend/src/channels/channels.controller.ts
backend/src/channels/channels.service.spec.ts
backend/src/channels/channels.service.ts

fix(backend): channels password are no longer sent

---

backend/src/relationships/friendships/friendships.service.ts

refactor(friendships): enforcing unique in both ways -target-source-

---

backend/src/chat/chat.gateway.ts
backend/src/memberships/memberships.service.ts
frontend/src/components/Chat/ChannelInviteDialog.vue
frontend/src/components/Chat/ChannelJoinDialog.vue
frontend/src/components/Chat/ChannelList.vue
frontend/src/components/Chat/ChatDmDialog.vue
frontend/src/components/Chat/ChatMessage.vue
frontend/src/components/Chat/ChatWindow.vue
frontend/src/views/ChatView.vue

- Fetches all messages on a channel instead of just the most recent 10
- Only show password field when channel is selected in JoinChannelDialog
- Move channel list to the left/top
- Put the timestamp into a tooltip
- Move the message and avatar onto a single line
- Removes useless console.logs (a few still remain in catch blocks)
- Clean up axios calls
Fix #346

Cleanup the ChatView and components

---

.github/workflows/frontend-ci.yml
backend/src/all-exceptions.filter.ts
backend/src/channels/channels.controller.ts
backend/src/chat/chat.gateway.ts
backend/src/game/ball.ts
backend/src/game/game.gateway.ts
backend/src/game/player.ts
backend/src/memberships/memberships.controller.ts
backend/src/messages/messages.controller.ts
backend/src/relationships/blocks/blocks.controller.ts
backend/src/relationships/friendships/friendships.controller.ts
dtos/game/create-game.dto.ts
dtos/game/game-options.dto.ts

Remove outdated comments and TODOs

style: remove outdated comments

---

frontend/src/components/Profile/MyFriends.vue

Sorry for this very late PR but it is very small, and even though we said that the correction didn't specify that we needed to be able to challenge from chat as well as from profile, in the current state we cannot challenge at all if the user we want to challenge never sent a message, which is really not a good look imo..

feat(profile): challenge when user is connected and not ingame

---

docker-compose.yml
frontend/vite.config.ts

Remove hot reload. To test:
- Change something in a page in front. The page shouldn't reload.
- /!\ check the console to see if an error appears

Remove hot reload

---

frontend/src/components/Chat/ChannelKarmaDialog.vue

feat(karma): change time scale to minutes

---

backend/package-lock.json

chore: update package-lock.json so it isn't modified each time

chore: update package-lock.json

---

frontend/src/components/Chat/ChatWindow.vue
frontend/src/views/ChatView.vue

- re-emit the chat-listen when a window opens

fix(chat): remove socket off

---

frontend/src/components/Login/FortyTwo.vue

Connection is smoother as a v-progress-circular is displayed

feat(frontend): smoother connection

---

.env.example
README.md
docker-compose.prod.yml
docker-compose.yml
frontend/src/components/Login/FortyTwo.vue

Differentiates the external port of the frontend and the port it is exposed to in the case of a reverse_proxy

fix(frontend): fixes the port of the frontend

---

.env.example
README.md
backend/src/auth/auth.controller.ts
backend/src/auth/google.strategy.ts
backend/src/config/configuration.ts
docker-compose.yml
frontend/Dockerfile.prod
frontend/src/components/Login/FortyTwo.vue
frontend/src/components/Login/NoAuth.vue
frontend/src/config/index.ts
frontend/src/plugins/axios.ts
frontend/src/views/ChatView.vue
frontend/src/views/GameView.vue

* sets the URL as an environment variable in place of the domain, port (and scheme)
* updates the README.md

fix!: sets the URL as an environment variable 
